pipeline:
  trigger_build:
    image: plugins/downstream
    server: https://cd.stq.cloud
    secrets: [ downstream_token ]
    fork: true
    repositories: [ sansare/kafka-connect ]
    when:
      event: push
      branch: master
